; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Firefly The PC Game"
#define MyAppVersion "1.10.1"
#define MyAppPublisher "VeeBee-er"
#define MyAppURL "https://boardgamegeek.com/thread/2996155/firefly-windows-pc-game"
#define MyAppExeName "FireflyKalidasa.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId=EB56A73F-D1D8-44DE-896B-FCF27F5E7436
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=C:\Games\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputBaseFilename=FireflyKalidasaSetupV{#MyAppVersion}
SetupIconFile=D:\Progs\GitHub\FireflyKalidasa\serenity.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Binaries >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Source: "D:\Progs\GitHub\FireflyKalidasa\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\FireFlyAIBot.exe"; DestDir: "{app}"; Flags: ignoreversion
;Source: "D:\Progs\GitHub\FireflyKalidasa\VerseMapTool.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\bin\SFTTREEX.OCX"; DestDir: "{sys}"; Flags: 32bit regserver sharedfile 
Source: "D:\Progs\GitHub\FireflyKalidasa\bin\MSCOMCTL.OCX"; DestDir: "{sys}"; Flags: 32bit regserver sharedfile
Source: "D:\Progs\GitHub\FireflyKalidasa\bin\LaVolpeAlphaImg2.ocx"; DestDir: "{sys}"; Flags: 32bit regserver sharedfile
Source: "D:\Progs\GitHub\FireflyKalidasa\bin\XDockFloat.dll"; DestDir: "{sys}"; Flags: 32bit regserver sharedfile
; FONTS >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Source: "D:\Progs\GitHub\FireflyKalidasa\bin\SHOWG.TTF";  DestDir: "{autofonts}"; FontInstall: "Showcard Gothic"; Flags: onlyifdoesntexist uninsneveruninstall
Source: "D:\Progs\GitHub\FireflyKalidasa\bin\bankgthd.ttf";  DestDir: "{autofonts}"; FontInstall: "BankGothic Md BT"; Flags: onlyifdoesntexist uninsneveruninstall
Source: "D:\Progs\GitHub\FireflyKalidasa\bin\BRITANIC.TTF";  DestDir: "{autofonts}"; FontInstall: "Britannic Bold"; Flags: onlyifdoesntexist uninsneveruninstall
Source: "D:\Progs\GitHub\FireflyKalidasa\bin\CIND.otf";  DestDir: "{autofonts}"; FontInstall: "Cyberpunk Is Not Dead"; Flags: onlyifdoesntexist uninsneveruninstall
Source: "D:\Progs\GitHub\FireflyKalidasa\bin\Forque.ttf";  DestDir: "{autofonts}"; FontInstall: "FORQUE"; Flags: onlyifdoesntexist uninsneveruninstall
Source: "D:\Progs\GitHub\FireflyKalidasa\bin\STENCIL.TTF";  DestDir: "{autofonts}"; FontInstall: "Stencil"; Flags: onlyifdoesntexist uninsneveruninstall
; Primary Files >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Source: "D:\Progs\GitHub\FireflyKalidasa\FireflyKalidasa.mdb"; DestDir: "{app}"; Flags: ignoreversion; Permissions: users-modify
Source: "D:\Progs\GitHub\FireflyKalidasa\FireflyKalidasa_FullBoard.mdb"; DestDir: "{app}"; Flags: ignoreversion; Permissions: users-modify
Source: "D:\Progs\GitHub\FireflyKalidasa\Firefly_rulebook.pdf"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\FireflyBlueSun_rulebook.pdf"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\FireflyKalidasa_rulebook.pdf"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\Firefly_Pirates_Bounty_Hunters_rulebook.pdf"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\FireflyForPC.pdf"; DestDir: "{app}"; Flags: ignoreversion
; PICTURES >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\amnon.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Atherton.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\AToken1.gif"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\AToken2.gif"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\AToken3.gif"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\AToken4.gif"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\AToken5.gif"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\AToken6.gif"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\badger.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Bester.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Billy.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\KalidasaBoard.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\KalidasaBoard1.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\FireflyFullBoard.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Bourne.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Bree.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Bridgit.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\browncoat.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Burgess.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\BurgessOrig.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\CargoBay.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Chari.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Corbin.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Cortland.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Crow.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\CryBaby.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\delta.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Deputy.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Dobson.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Doralee.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Dress.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\ellie.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Emma.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Ensign.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Explosives.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Fendris.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\flyingmule.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Guardian.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Gran.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Grange.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\harken.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\harrow.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Helen.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\HeadGoon.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Holder.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Hotspot.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Inara.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Jayne.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\JaynesHat.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Jed.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Jesse.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\patron.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Kaylee.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\KReprogammer.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\logo.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Lucy.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Lund.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Malcolm.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\MaqueTiles.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Marco.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Marshal.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Monty.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\MrUniverse.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Murphy.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Nandi.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\niska.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\OriginalBoard.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\OverChg.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Parasol.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Patience.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Quarters.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\River.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\RToken1.gif"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\RToken2.gif"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\RToken3.gif"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\RToken4.gif"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\RToken5.gif"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\RToken6.gif"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Saffron.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Shepherd.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Sheydra.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Simon.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Skunk.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Skyhook.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Stark.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Stitch.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Tracey.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\timebomb.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Two-Fry.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Wash.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Womack.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Yolonda.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Zoe.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\wright.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmWright.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\boardgame.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\fantymingo.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\inarasbow.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\higgins.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\4WDmule.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Vera.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\FireflyBlue.gif"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\FireflyYellow.gif"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\FireflyOrange.gif"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\FireflyGreen.gif"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Cruiser.gif"; DestDir: "{app}\pictures"; Flags: ignoreversion           
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Corvette.gif"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Cutter.gif"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\barkeepbob.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\barkeepbex.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\fess.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\4range.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\6range.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\ambo.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\baton.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\billiards.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\BurgessLaser.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\clips.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\creds.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\crowsknife.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\dc6range.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\dc6rangeII.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\docs.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\flac.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\foam.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Glucklich.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\grenade.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\guild.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\hfdocs.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\horses.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\ident.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\ImproHack.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Intel.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Jacket.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\jaynesPistol.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\kit.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\knife.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\lovebot.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\malspistol.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\medbay.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\necktie.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\oatbar.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\pistol.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Radion.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SecInterPad.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\shirt.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\sniper.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SpaceJeep.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\sword.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\washcharts.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\YolondaPistol.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\zoerifle.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\suit1.bmp"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\suit2.bmp"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\suit3.bmp"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\suit4.bmp"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\D1.bmp"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\D2.bmp"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\D3.bmp"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\D4.bmp"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\D5.bmp"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\D6.bmp"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\haven1.bmp"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\haven2.bmp"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\haven3.bmp"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\haven4.bmp"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\fight.bmp"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\tech.bmp"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\nego.bmp"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Foreman.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\draper.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\roberta.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\busker.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\middleman.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\maddi.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\max.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\maz.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\McGinnis.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\moo.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\mic.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\moi.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\grimey.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\fandancer.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\salesman.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\recycler.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smharken.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smlogo.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Jubal.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\CrewTemplate.bmp"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\GearBlank.bmp"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\MisbehaveTemplate.bmp"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\ShipUpgrdBlank.bmp"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\smsuit1.bmp"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\smsuit2.bmp"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\smsuit3.bmp"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\smsuit4.bmp"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\skill1.bmp"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\skill2.bmp"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\skill3.bmp"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\bonnet.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\dinosaurs.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\inarashuttle.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\drshuttle.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\survshuttle.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Nav1_A.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Nav1_B.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Nav1_R.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Nav2_A.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Nav2_B.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Nav2_R.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Salvage.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\bestinthehouse.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\shades.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\InarasKnife.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Encyclopedia.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\mediczen.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\mediczil.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\mediczee.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\mediczox.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\fixer.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\interrogator.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\boarded.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\kamal.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\enforcerbo.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\enforcerdon.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\enforcerron.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\enforcerzoh.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\gunhandgil.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\gunhandgin.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\gunhandjim.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\gunhandjoh.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\gunhandrex.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\gunhandron.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\gunhandtex.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\gunhandtim.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\gunhandtom.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\gunhandtom.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\specialist.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\ScrapperJox.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\ScrapperMex.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\ScrapperPoh.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\ScrapperVin.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\ScrapperVix.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\ScrapperVox.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\helmsman.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\helmsman2.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Dalin.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\hat.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\washcharts.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\navchartsalliance.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\navchartsborder.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\navchartsrim.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\navchartswormhole.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\identguest.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\vektorpistol.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\waiting.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\showdown.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion

; Smalls >>>>>>>>
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmAtherton.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmBurgess.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmCorbin.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmDobson.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmMalcolm.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmMarco.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmMonty.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmMurphy.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmNandi.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smpatron.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmWomack.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmSimon.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmJayne.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmRiver.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmZoe.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmShepherd.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmKaylee.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmInara.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmWash.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmBarkeepBex.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmBarkeepBob.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmBester.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmBilly.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmBourne.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmBree.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmBridgit.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmBusker.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmChari.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmCortland.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmCrow.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smdelta.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmDeputy.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmDoralee.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smdraper.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmEmma.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmEnsign.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smfandancer.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmFendris.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smfess.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmForeman.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smgran.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmGrange.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmGrimey.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmGuardian.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smgunhandgil.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smgunhandgin.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smgunhandjim.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smgunhandjoh.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smgunhandrex.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smgunhandron.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smgunhandtex.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smgunhandtim.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smgunhandtom.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smgunhandtom.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmHelen.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmHeadGoon.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmHolder.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmJed.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmJesse.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmJubal.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmLucy.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmLund.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmMaddi.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmMarshal.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmMax.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmMaz.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmMcGinnis.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmMic.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmMiddleman.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmMoi.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmMoo.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmRoberta.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmSaffron.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmSalesman.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smkamal.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmSheydra.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmSkunk.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmStark.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmStitch.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmTimebomb.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmTracey.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmTwo-Fry.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmYolonda.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmGoal.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smbounty.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smmediczox.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smmediczee.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smmediczen.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smmediczil.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smfixer.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Sminterrogator.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smspecialist.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smharrow.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmMrUniverse.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smniska.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmPatience.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smhiggins.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smfantymingo.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smamnon.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smbadger.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smenforcerbo.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smenforcerdon.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smenforcerron.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smenforcerzoh.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmScrapperJox.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmScrapperMex.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmScrapperPoh.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmScrapperVin.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmScrapperVix.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmScrapperVox.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smhelmsman.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Smhelmsman2.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\SmDalin.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\array.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\catalyzer.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\chopshop.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\compressioncoils.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\dockingclamps.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\reaverflage.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\smuggling.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion

; GUI >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Action1FlyActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Action2BuyActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Action3DealActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Action4WorkActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Action5BonusActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Actionbg.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Bonus1MoraleActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Bonus1MoraleClick.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Bonus1MoraleInactive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Bonus1MoraleMouseover.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Bonus2AlertsActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Bonus2AlertsClick.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Bonus2AlertsInactive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Bonus2AlertsMouseover.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Buy1ConsiderActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Buy1ConsiderClick.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Buy1ConsiderMouseover.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Buy1DrawActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Buy1DrawClick.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Buy1DrawMouseover.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Buy1FinishActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Buy1FinishClick.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Buy1FinishMouseover.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Buy1ShopActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Buy1ShopClick.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Buy1ShopInactive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Buy1ShopMouseover.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Buy2ShoreLeaveActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Buy2ShoreLeaveClick.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Buy2ShoreLeaveInactive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Buy2ShoreLeaveMouseover.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Buy3FuelActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Buy3PartsActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Contact1.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Contact2.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Contact3.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Contact4.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Contact5.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Contact6.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Contact7.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Contact8.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Contact9.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Deal1ConsiderActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Deal1ConsiderClick.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Deal1ConsiderMouseover.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Deal1DrawAvailable.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Deal1DrawClick.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Deal1DrawMouseover.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Deal1FinishAvailable.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Deal1FinishClick.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Deal1FinishMouseover.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Deal1LocalActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Deal1LocalClick.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Deal1LocalInactive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Deal1LocalMouseover.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Deal3PhoneActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Deal3PhoneClick.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Deal3PhoneInactive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Deal3PhoneMouseover.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Deal4ReadActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Deal4ReadClick.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Deal4ReadInactive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Deal4ReadMouseover.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Deal5CargoActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Deal5ContraActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Deal5FuelActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Deal5FugiActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Deal5PartsActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Deal5PassActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Deal5WarrantsActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Deal5WarrantsOptActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Deal5WarrantsOptClick.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Deal5WarrantsOptInactive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\End1EndActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\End1EndClick.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\End1EndInactive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\End1EndMouseover.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\End2CancelActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\End2CancelClick.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\End2CancelMouseover.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Firefly1.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Firefly2.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Firefly3.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Firefly4.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Fly1FullBurnActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Fly1FullBurnClick.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Fly1FullBurnInactive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Fly1FullBurnMouseover.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Fly2MoseyActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Fly2MoseyClick.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Fly2MoseyInactive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Fly2MoseyMouseover.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Fly3BoostActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Fly3BoostClick.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Fly3BoostInactive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Fly3BoostMouseover.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Fly4MoleActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Fly4MoleClick.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Fly4MoleInactive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Fly4MoleMouseover.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\FlyBreakdownProofActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\FlyHeavyLoadActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Header2GoalsActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Header3WarrantsActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Header4OutlawActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Supply1.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Supply2.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Supply3.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Supply4.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Supply5.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Supply6.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Supply7.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Work1LocalActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Work1LocalArrow.gif"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Work1LocalClick.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Work1LocalInactive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Work1LocalMouseover.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Work2MakeActive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Work2MakeClick.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Work2MakeInactive.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\Work2MakeMouseover.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\tileEvents.bmp"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\FireflyBoard1.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\FireflyBoard2.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\FireflyBoard3.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\gui\FireflyBoard4.jpg"; DestDir: "{app}\gui"; Flags: ignoreversion

; Solids >>>>>>>>
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Solid1harken.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Solid1harrow.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Solid1MrUniverse.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Solid1niska.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Solid1Patience.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Solid1higgins.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Solid1fantymingo.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Solid1amnon.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Solid1badger.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Solid2harken.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Solid2harrow.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Solid2MrUniverse.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Solid2niska.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Solid2Patience.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Solid2higgins.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Solid2fantymingo.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Solid2amnon.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\pictures\Solid2badger.jpg"; DestDir: "{app}\pictures"; Flags: ignoreversion

; SOUNDS >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Source: "D:\Progs\GitHub\FireflyKalidasa\sounds\Alert.WAV"; DestDir: "{app}\sounds"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\sounds\Beep.wav"; DestDir: "{app}\sounds"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\sounds\Burn.wav"; DestDir: "{app}\sounds"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\sounds\Cruiser.wav"; DestDir: "{app}\sounds"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\sounds\mosey.wav"; DestDir: "{app}\sounds"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\sounds\msg.wav"; DestDir: "{app}\sounds"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\sounds\no.wav"; DestDir: "{app}\sounds"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\sounds\Reaver.wav"; DestDir: "{app}\sounds"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\sounds\Win.wav"; DestDir: "{app}\sounds"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\sounds\yourgo.wav"; DestDir: "{app}\sounds"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\sounds\gear.wav"; DestDir: "{app}\sounds"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\sounds\reload.wav"; DestDir: "{app}\sounds"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\sounds\clack.wav"; DestDir: "{app}\sounds"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\sounds\Sonar.wav"; DestDir: "{app}\sounds"; Flags: ignoreversion
Source: "D:\Progs\GitHub\FireflyKalidasa\sounds\Wormhole.wav"; DestDir: "{app}\sounds"; Flags: ignoreversion

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{#MyAppName} Full Map"; Filename: "{app}\{#MyAppExeName}"; Parameters: "{app}\FireflyKalidasa_FullBoard.mdb"
;Name: "{group}\{#MyAppName} on MariaDB"; Filename: "{app}\{#MyAppExeName}"; Parameters: "Provider=MSDASQL;Driver={{MariaDB ODBC 3.1 Driver};Server=blis.duckdns.org;Port=3306;"
Name: "{group}\Firefly AI Bot"; Filename: "{app}\FireFlyAIBot.exe"
Name: "{group}\Firefly Rulebook"; Filename: "{app}\Firefly_rulebook.pdf"
Name: "{group}\BlueSun Rulebook"; Filename: "{app}\FireflyBlueSun_rulebook.pdf"
Name: "{group}\Kalidasa Rulebook"; Filename: "{app}\FireflyKalidasa_rulebook.pdf"
Name: "{group}\Firefly-for-PC Guide"; Filename: "{app}\FireflyForPC.pdf"

Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

